### ISSUE TITLE
django-secure should discourage cookie backed session stores

### ISSUE THREAD

**Issue by PaulMcMillan** [carljm/django-secure#2]
It's not terribly likely that people will be using cookie backed session stores if they're worried about security, but they might. To the best of my knowledge, the signing on these is secure. Nonetheless, django-secure should probably discourage their use.

(This might not quite fall into the "you're doing it wrong" category... maybe there should be a different set of tests that will tell you "be very very careful if you're doing any of these things". More of a django-security-lint kind thing.)

**Comment by carljm** [comment]
Closing all open issues - I've decided not to continue maintaining django-secure as an external project, since all of its functionality was merged into Django 1.8, which is now (or will shortly be) the lowest supported Django version.
