### ISSUE TITLE
Possible features: Check database security?

### ISSUE THREAD

**Issue by puterleat** [carljm/django-secure#31]
I wonder if you've considered checking whether the user to which the app connects has "too many" privileges in the database, and whether the DB connection itself is secure. 

I just went through the process of testing whether my app on heroku was connecting to an Amazon RDS instance over SSL or not. It turns out that you can check this with the following code:

    from django.db import connection
    cursor = connection.cursor()
    cursor.execute("show ssl")
    assert  cursor.fetchone()[0] ==  "on"

Provided the sslinfo extension is running (see http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.SSL) 

It did also make me thing whether there are easy pickings, eg. to check that the app is not connecting to the DB as an admin user? It's kind of relevant when many people are doing their own sysadmin and dbadmin for small hobby projects.

**Comment by carljm** [comment]
The future of this app is a bit unclear; it's been merged into Django 1.8, so at this point it's only useful as a backport for older Django versions. It's possible we could add more checks and keep it alive as an extension of the built-in checks in Django 1.8+, but really I think any new checks should probably just be added to Django directly at this point.

Aside from that issue, I'd certainly be open to a PR for this.

**Comment by carljm** [comment]
Closing all open issues - I've decided not to continue maintaining django-secure as an external project, since all of its functionality was merged into Django 1.8, which is now (or will shortly be) the lowest supported Django version.
