### ISSUE TITLE
SSL redirect optionally for GET requests only

### ISSUE THREAD

**Issue by johannesschirrmeister** [carljm/django-secure#33]
I was wondering if it were useful for others as well if the SSL redirect mechanism could be restricted to GET requests only. This would be helpful for a site that would like to enable the SSL redirect, but receives non-HTTPS POST requests to a lot of different endpoints. Some clients would either not follow the redirect or switch to GET when making the second request using the new HTTPS location, which would not result in the intended action.

Put differently, what do you think adding the following config option?
```ssl_redirect_supported_http_methods = GET```

**Comment by carljm** [comment]
Hi! Thanks for the suggestion. My feeling is that this introduces too much complexity for an edge case. The SSL-redirect portion of the middleware is very simple (well, all of django-secure is pretty simple), so it's very easy to roll your own middleware for your particular needs. The intended use case for django-secure is for where _all_ requests should always be HTTPS.
