### ISSUE TITLE
Document status versus 1.8

### ISSUE THREAD

**Issue by dokterbob** [carljm/django-secure#34]
It seems that all or most of the features of this package have made it into the mainline of Django. However, whether it is all or most is not clear. Also, it is not clear whether this package will be maintained in some form or other.

It would be great to find this back in the README and/or other documentation.

Thanks!

**Comment by carljm** [comment]
Yes, thanks for the nudge, I'll update the docs. The answers are "yes, it was all merged into Django 1.8" and "no, I don't plan to maintain django-secure any longer" now that 1.8 is (or will shortly be) the minimum supported Django version.

**Comment by carljm** [comment]
Fixed.
